In [1]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees , departments , on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees , departments , on="DeptID" , how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [9]:
pd.merge(employees , departments , on="DeptID" , how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [10]:
pd.merge(employees , departments , on="DeptID" , how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing